name: flutter_clean_architecture_exemple
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0

  # Networking
  dio: ^5.7.0
  retrofit: ^4.9.0

  # Navigation
  go_router: ^14.6.2

  # Local Database
  drift: ^2.24.2
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: ^1.9.0

  # Code Generation Annotations
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit_generator: ^10.2.0

  # UI Utils
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^3.0.0
  freezed: ^3.0.0
  json_serializable: ^6.9.0
  drift_dev: ^2.24.2
  
  
  
  

flutter:
  uses-material-design: true
